nodeLinker: node-modules

compressionLevel: mixed

enableGlobalCache: false

npmPublishAccess: public

npmScopes:
  cbnsndwch:
    npmPublishRegistry: https://registry.npmjs.org/
    npmRegistryServer: https://registry.npmjs.org/

yarnPath: .yarn/releases/yarn-4.1.1.cjs
